### ISSUE TITLE
FEEDBACK action trouble with LRC protocol

### ISSUE THREAD

**Issue by o2sport** [bitfocus/companion-module-imagine-lrc#3]
Hello, I would like to thank you for this plugin.

We are in a state of implementation a new Matrix from Evertz. For controling we are using CEREBRUM software and ELGATO as UI.

CEREBRUM make communication between EVERTZ matrix and Companion SW thru LRC protocol. All switching works well but we have a problem with feedback. I set up change color for button if crosspoint is sets but no colorchange on button.

I want to download a manual from imagine sites but after registration all section for download are empty.

Could you send me link for manual or help me with my problem?

Thank You
David

**Comment by RossIV** [comment]
I don't have access to anything Evertz so my ability to help will be limited, but I can certainly give it a shot.

The crosspoint feedback relies upon the LRC server sending a `~XPOINT!` message over the socket that Companion opens. For example, `~XPOINT!D${SHD MON};S${CAM PM 2}\` which indicates a crosspoint of Destination `SHD MON` and Source `CAM PM 2`. Some equipment doesn't use source/destination names but numbers (likely for legacy compatibility), e.g. `~XPOINT!D#{64};S#{60}\`. Either format is supported by this module.

All received crosspoint state changes are sent to the Companion debug logs. In the Companion UI, go to the `Log` tab then click `Debug` if debug logs aren't already being displayed. If a valid crosspoint state change message is being received, you should see a message for it, e.g. `YY.MM.DD HH:MM:SS instance(lrc-instance-name): Crosspoint State Updated: SHD MON:CAM PM 2`. You may also see `Destination 'ZZZZ' not found, can't update state` if the destination in the message isn't one that was returned from the module's query of the server. If you don't see messages like either of those, then either the LRC server isn't sending them or they're in a different format that the module currently doesn't handle. Check the logs for those messages and let me know what you do or don't see. 

If you don't see any logs for crosspoints, then things get a bit more complicated. The module doesn't currently log messages received from the LRC server that don't match a known format or are otherwise not able to be processed. The easiest way to capture raw LRC messages is using a Telnet client (e.g. PuTTY). Open a connection to the LRC server's IP on the appropriate port (e.g. 52116). Whenever a LRC message is sent, it should be displayed in your session. Once you have the session open, send some crosspoint commands from Companion (or other controller). You should hopefully see several messages in the session. Each message starts with a `~` and ends with a `\`. In my experience, there are no carriage returns or newline characters, so you may want to take the output into a text editor for easier viewing. Feel free to reply with a sampling of those messages here and I can try to see why they're not being handled.

**Comment by Jeffulka** [comment]
Hello RossIV

**Comment by RossIV** [comment]
My apologies for the delay in getting this fixed. For your use would you need the crosspoints and locks to include levels, or if I added an option to ignore levels entirely would that work?

**Comment by RossIV** [comment]
Closing stale issues, if still needed please comment back.
